### ISSUE TITLE
calculatePrival has some bugs

### ISSUE THREAD

**Issue by sjanecki** [squeeks/glossy#1]
https://github.com/squeeks/glossy/blob/master/lib/glossy/produce.js#L415

What if pri.severity is equals 0 (which is severity  'emerg': 0, ) ??
It will become falsy and and will jump to else statment and return false!

the same thing with  pri.facility  'kern':   0

**Comment by bizob2828** [comment]
This piece seems to work ok but it depends on how you call produce.  I use `winston-syslog` and it doesn't pass in facility when it calls .produce. So when it gets to this line, https://github.com/squeeks/glossy/blob/master/lib/glossy/produce.js#L154, this.facility is undefined because it will never set this.facility https://github.com/squeeks/glossy/blob/master/lib/glossy/produce.js#L114.  It looks like there hasn't been a release in man years but if I open a PR would it get some 👀 ?
