### ISSUE TITLE
syslogProducer.produce is undefined

### ISSUE THREAD

**Issue by rcrichton** [squeeks/glossy#32]
I'm having a problem with the producer. When I require the syslogProducer the `.produce` function is undefined. This seems to be the case in all of the producer examples from the readme.

```js
const glossy = require('glossy');
const syslogProducer = glossy.Produce;
const syslogParser = glossy.Parse;

console.log(syslogParser.parse);
console.log(syslogProducer.produce);

// Output:
// [Function]
// undefined
```

**Comment by rcrichton** [comment]
So, it seems that the readme is wrong. It seems we need to do something like this instead:

```js
const glossy = require('glossy');
const syslogProducer = new glossy.Produce();
const syslogParser = glossy.Parse;
```

It's a little strange that the parser and producer are handled differently. For the producer.js just the class function is exported where as for the parser a object instance is exported. Perhaps this should be normalised so that both exports only export the class function for consitency. So, it will end up looking like this:

```js
const glossy = require('glossy');
const syslogProducer = new glossy.Produce();
const syslogParser = new glossy.Parse();
```

**Comment by squeeks** [comment]
It was designed like that because the parser doesn't take any arguments and can distinguish between 3164/5424 messages just by looking at them, however producers take arguments so they know what format to output with.

I don't have any objections to normalising this, however I won't be doing the work I'm afraid. Please raise a pull request if you'd like, but do please keep the code ES5.

**Comment by rcrichton** [comment]
Ok cool. I may have a look at this sometime, but it's not too important for now. You may just want to update the documentation to be correct. The code in the producing documentation is wrong.
